---
- hosts: 43.205.235.80
  become: yes
  remote_user: ec2-user
  tasks:
  - name: Installing apache middleware
  yum:
  name: httpd
  state: present
  - name: starting apache
  service:
  name: httpd
  state: started
   
